name: iochat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Do not change version here. Set version in codemagic.yaml e.g. BUILD_NAME: 5.0.0 (BUILD_NUMBER is dynamically created by script)
version: 1.0.0+0 

environment:
  sdk: '>=3.0.0 <4.0.0' # dart

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_keychain: 2.4.0             # Publisher appmire.be, Flutter secure storage via Keychain and Keystore.
  permission_handler: 11.0.1          # Publisher baseflow.com, provides API to request permissions
  open_filex: 4.3.4                   # Publisher buildtoapp.com, A plug-in that can call native APP to open files with string result in flutter 

  flutter_app_badger: 1.5.0           # Publisher daad.mobi, plugin to update the app badge on the launcher (both for Android, iOS and macOS)
  provider: 6.0.5                     # Publisher dash-overflow.net, a wrapper around InheritedWidget to make them easier to use and more reusable.
  flutter_local_notifications: 16.1.0 # Publisher dexterx.dev, a cross platform plugin for displaying local notifications.
  flutter_svg: 2.0.7                  # Publisher dnfield.dev, an SVG rendering and widget library.

  http: 0.13.6                        # Publisher dart.dev, a composable, multi-platform, Future-based API for HTTP requests.
  path_provider: 2.1.1                # Publisher flutter.dev, a plugin for finding commonly used locations on the filesystem.
  url_launcher: 6.1.14                # Publisher flutter.dev, used for launching Url to external application.
  
  cloud_firestore: 4.14.0             # Publisher firebase.google.com, Flutter plugin for Cloud Firestore.
  firebase_auth: 4.16.0               # Publisher firebase.google.com, Flutter plugin for Firebase Auth
  firebase_core: 2.24.2               # Publisher firebase.google.com
  firebase_core_platform_interface: 5.0.0
                                      # Publisher firebase.google.com, a plugin to use the Firebase Platform.
  firebase_messaging: 14.7.0          # Publisher firebase.google.com, a plugin to use the Firebase Cloud Messaging API.

  get_it: 7.6.4                       # Publisher fluttercommunity.dev, accessing an object from anywhere, service locator.
  flutter_downloader: 1.11.4          # Publisher fluttercommunity.dev, a plugin for creating and managing download tasks.
  package_info_plus: 4.0.0            # Publisher fluttercommunity.dev, provides an API for querying information about an application package.

  flutter_inappwebview: 6.0.0-rc.1
                                      # Publisher inappwebview.dev, a Flutter plugin that allows you to add an inline webview, to use an headless webview, and to open an in-app browser window.

  flutter_web_auth: 0.5.0             # Publisher unverified, a plugin for authenticating a user with a web service.
  uni_links: 0.5.1                    # Publisher unverified, a plugin for accepting incoming links - App/Deep Links (Android), Universal Links and Custom URL schemes (iOS).
  simple_shadow: 0.3.1                # Publisher unverified, a customizable shadow for any widget.
  receive_sharing_intent: 1.4.5       # Publisher unverified, a flutter plugin that enables flutter apps to receive sharing photos, text or url from other apps.

  # White label dependencies
  change_app_package_name: 1.1.0      # Publisher atiq.dev, change App Package Name with single command. It makes the process very easy and fast.
  flutter_config: 2.0.2               # Publisher byneapp.com, Plugin that exposes environment variables to your Dart code in Flutter as well as to your native code in iOS and Android.
  flutter_launcher_icons: 0.13.1      # Publisher fluttercommunity.dev, a package which simplifies the task of updating your Flutter app's launcher icon.
  rename: 3.0.1                       # Publisher onatcipli.com, it helps you to change your flutter project's AppName and BundleId for different platforms.

  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/launcher/
    - assets/images/
    - assets/fontawesome/light/
    - assets/fontawesome/regular/
    - assets/fontawesome/solid/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# dynamic icon change config
flutter_launcher_icons:
  ios: "AppIcon"
  image_path_ios: 'assets/launcher/ios_icon.png'
  android: "ic_launcher"
  image_path_android: 'assets/launcher/android_icon.png'
  adaptive_icon_foreground: 'assets/launcher/android_foreground.png'
  adaptive_icon_background: 'assets/launcher/android_background.png'
  min_sdk_android: 27